// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupJSON() {
  return window['go']['main']['App']['BackupJSON']();
}

export function CreateEntry(arg1) {
  return window['go']['main']['App']['CreateEntry'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function GetMeta() {
  return window['go']['main']['App']['GetMeta']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function HttpHandler() {
  return window['go']['main']['App']['HttpHandler']();
}

export function ImportBatch(arg1, arg2) {
  return window['go']['main']['App']['ImportBatch'](arg1, arg2);
}

export function ListEntries(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListEntries'](arg1, arg2, arg3);
}

export function RelocateEntries(arg1, arg2, arg3) {
  return window['go']['main']['App']['RelocateEntries'](arg1, arg2, arg3);
}

export function UpdateEntry(arg1) {
  return window['go']['main']['App']['UpdateEntry'](arg1);
}
