// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {http} from '../models';

export function BackupJSON():Promise<Array<main.Entry>>;

export function CreateEntry(arg1:main.Entry):Promise<main.Entry>;

export function DeleteEntry(arg1:number):Promise<void>;

export function GetMeta():Promise<Array<main.BuildingMeta>>;

export function GetStats():Promise<main.Stats>;

export function HttpHandler():Promise<http.Handler>;

export function ImportBatch(arg1:string,arg2:Array<main.Entry>):Promise<number>;

export function ListEntries(arg1:string,arg2:string,arg3:string):Promise<Array<main.Entry>>;

export function RelocateEntries(arg1:Array<number>,arg2:string,arg3:string):Promise<number>;

export function UpdateEntry(arg1:main.Entry):Promise<main.Entry>;
